from django.urls import path
from . import views

app_name="pswms"

urlpatterns=[
    
    path('',views.ProjectHome,name="project_home"),
    path('Login',views.CommonLogin,name="common_login"),
    path('About',views.ProjectAbout,name="prj_about"),
    path('AdminData',views.AdminData), # to add admin data once in database
    path('SuperHome',views.SuperHome,name="super_home"),
    path('SuperHome/AddPanchayath',views.AddPanchayath,name="add_panchayath"),
    path('SuperHome/AddWard',views.AddWard,name="add_ward"),
    path('SuperHome/WardDelete/<int:ward_id>',views.DeleteWard,name="delete_ward"),
    path('SuperHome/AddNotification',views.AddNotification,name="add_notification"),
    path('SuperHome/DeleteNotification/<int:n_id>',views.DeleteNotification,name="delete_notfn"),
    path('SuperHome/download/<int:u_id>',views.AdminDownloadUserData,name="pdf_admin_user"),
    path('SuperHome/ViewAllMembers',views.ViewAllMembers,name="view_all_members"),
    path('SuperHome/DelPan/<int:p_id>',views.DeletePanchayath,name="delete_pan"),
    path('SuperHome/AddBin',views.AddBin,name="add_bin"),
    path('SuperHome/BinDelete/<int:bin_id>',views.DeleteBin,name="delete_bin"),
    path('SuperHome/DeleteMember/<int:member_id>',views.DeleteMember,name="delete_member"),
    path('SuperHome/AddWaste',views.AddWaste,name="add_waste"),
    path('SuperHome/AddMember',views.AddPanchayathMember,name="add_member"),
    path('SuperHome/ViewUsers',views.AdminViewUsers,name="admin_view_users"),
    path('SuperHome/WasteDelete/<int:w_id>',views.WasteDelete,name="delete_waste"),
    path('SuperHome/ViewComplaint',views.AdminViewComplaint,name="admin_view_complaint"),
    path('SuperHome/MemberComplaint',views.MemberComplaint,name="member_complaint"),
    path('SuperHome/ReplyUser',views.ReplyUser,name="reply_user"),
    path('SuperHome/BarChart',views.BarChart,name="admin_chart"),

    path('MemberHome',views.MemberHome,name="member_home"),
    path('MemberHome/UpdateProfile',views.MemberUpdateProfile,name="update_profile"),
    path('MemberHome/ChangePasswd',views.MemberChangePasswd,name="member_change_passwd"),
    path('MemberHome/PendingUsers',views.PendingUsers,name="pending_users"),
    path('MemberHome/Approve/<int:user_id>',views.ApproveUser,name="approve_user"),
    path('MemberHome/Reject/<int:user_id>',views.RejectUser,name="reject_user"),
    path('MemberHome/ViewUsers',views.ViewAllUsers,name="view_users"),
    path('MemberHome/DeleteUsers/<int:user_id>',views.DeleteUsers,name="delete_users"),
    path('MemberHome/ViewNotifications',views.ViewNotifications,name="view_notifications"),
    path('MemberHome/PendingRequest',views.PendingPickUpRequest,name="pending_request"),
    path('MemberHome/RequestDetails',views.RequestDetails,name="request_details"),
    path('MemberHome/DriverReg',views.DriverRegistration,name="add_driver"),
    path('MemberHome/ViewDriver',views.ViewDriver,name="view_driver"),
    path('MemberHome/DeleteDriver/<int:driver_id>',views.DeleteDriver,name="delete_driver"),
    path('MemberHome/download/<int:u_id>',views.DownloadUserData,name="pdf_user"),
    path('MemberHome/Block/<int:user_id>',views.BlockUser,name="block_user"),
    path('MemberHome/AddSign',views.MemberSign,name="member_sign"),
    path('getPrice',views.getPrice,name="get_price"),
    # path('MemberHome/SearchUser',views.SearchUser,name="search_user"),
    path('MemberHome/ViewComplaint',views.ViewComplaint,name="view_complaint"),
    path('MemberHome/ViewPayment',views.ViewPayment,name="view_payment"),
    path('MemberHome/PaymentDetails',views.PaymentDetails,name="payment_details"),
    path('getWard',views.getWard,name="get_ward"),
    path('MemberHome/CompletedWork',views.CompletedWorks,name="view_completed_works"),
    path('MemberHome/Reply',views.MemberReplyUser,name="member_reply_user"),
    path('MemberHome/MemberChart',views.MemberChart,name="member_chart"),

    path('UserReg',views.UserRegistration,name="user_reg"),
    path('UserHome',views.UserHome,name="user_home"),
    path('UserHome/UpdateUserProfile',views.UpdateUserProfile,name="updateuser_profile"),
    path('UserHome/AddComplaint',views.AddComplaint,name="add_complaint"),
    path('UserHome/ChangeUserPasswd',views.ChangeUserPasswd,name="change_user_passwd"),
    path('UserHome/WasteRequest',views.WastePickUpRequest,name="waste_request"),
    path('UserHome/PaymentHistory',views.PaymentData,name="payment_history"),
    path('UserHome/ViewPaymentHistory',views.PaymentHistory,name="view_payment_history"),
     path('UserHome/AssignedDriver',views.AssignedDriver,name="assigned_driver"),
    # path('MemberHome/PendingRequest',views.PendingPickUpRequest,name="pending_request"),
    
    path('DriverHome',views.DriverHome,name="driver_home"),
    path('DriverHome/ViewWorkDetails',views.ViewWorkDetails,name="work_details"),
    path('DriverHome/PendingWorks',views.PendingWorks,name="pending_works"),
    path('DriverHome/CompletedWorks',views.DriverCompletedWorks,name="completed_works"),
    path('DriverHome/ChangeDriverPasswd',views.ChangeDriverPasswd,name="change_driver_passwd"),
    path('Logout',views.Logout,name="user_logout"),
    path('ForgotPassword/<str:login_id>',views.ForgotPassword,name="forgot_password"),

]