# Generated by Django 3.1.7 on 2021-05-29 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempryrequest',
            name='ward_id',
            field=models.ForeignKey(db_column='ward_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementApp.warddetails'),
        ),
    ]
