# Generated by Django 3.1.7 on 2021-05-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0002_tempryrequest_ward_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempryrequest',
            name='member_id',
        ),
    ]
