# Generated by Django 3.1.7 on 2021-05-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0003_remove_tempryrequest_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequestdetails',
            name='payment_status',
            field=models.CharField(db_column='pay_status', default='pending', max_length=20),
        ),
    ]
