# Generated by Django 3.1.7 on 2021-06-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0004_wasterequestdetails_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetails',
            name='reci_type',
            field=models.CharField(db_column='recipient_type', default='', max_length=200),
        ),
    ]
