# Generated by Django 3.1.7 on 2021-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0005_complaintdetails_reci_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintdetails',
            name='reci_type',
        ),
        migrations.AddField(
            model_name='complaintdetails',
            name='recipient_type',
            field=models.CharField(db_column='r_type', default='', max_length=200),
        ),
    ]
