# Generated by Django 3.1.7 on 2021-06-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0006_auto_20210612_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdetails',
            name='recipient_type',
            field=models.IntegerField(db_column='r_type', default=None),
        ),
    ]
