# Generated by Django 3.1.7 on 2021-06-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0007_auto_20210612_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetails',
            name='ward_id',
            field=models.ForeignKey(db_column='w_id', default=4, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementApp.warddetails'),
        ),
    ]
