# Generated by Django 3.1.7 on 2021-06-12 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0008_complaintdetails_ward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdetails',
            name='admin_reply',
            field=models.CharField(db_column='reply', default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='complaintdetails',
            name='ward_id',
            field=models.ForeignKey(db_column='w_id', on_delete=django.db.models.deletion.CASCADE, to='WasteManagementApp.warddetails'),
        ),
    ]
