# Generated by Django 3.1.7 on 2021-06-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0009_auto_20210612_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintdetails',
            old_name='admin_reply',
            new_name='reply',
        ),
    ]
