# Generated by Django 3.1.7 on 2021-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0010_auto_20210616_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetails',
            name='driver_language',
            field=models.CharField(db_column='d_language', default='empty', max_length=200),
        ),
        migrations.AddField(
            model_name='driverdetails',
            name='driver_qualification',
            field=models.CharField(db_column='d_qualification', default='empty', max_length=250),
        ),
    ]
