# Generated by Django 3.1.7 on 2021-07-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagementApp', '0011_auto_20210619_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequestdetails',
            name='pan_id',
            field=models.ForeignKey(db_column='pan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='WasteManagementApp.panchayathdetails'),
        ),
    ]
